# Generated by Django 5.0.3 on 2025-04-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
